plugins {
    id 'com.android.application'
    id "jacoco"
    id "org.sonarqube" version "4.4.1.3373"
}

sonar {
    properties {
        property "sonar.projectKey", "gitea_eo1"
        property "sonar.organization", "gitea"
        property "sonar.host.url", "https://sonarcloud.io"
        // To avoid implicit compilation, set property 'sonar.gradle.skipCompile' to 'true' and make sure your project is compiled, before analysis has started.
        property "sonar.gradle.skipCompile", true
        property "sonar.sources", "src/main/java"
        property "sonar.junit.reportsPath", "build/test-results/*/TEST-*.xml"
        property "sonar.tests", "src/test/java"
    }
}

android {
    namespace 'com.aphex3k.eo1'
    compileSdk 34

    defaultConfig {
        applicationId "com.aphex3k.eo1"
        minSdk 19
        //noinspection ExpiredTargetSdkVersion,OldTargetApi
        targetSdk 19
        maxSdk 19
        if (project.hasProperty('BUILD_NUMBER')) {
            versionCode = Integer.parseInt(project.BUILD_NUMBER)
        }
        else {
            versionCode = 1
        }
        versionName "1.1.4"
        multiDexEnabled true
    }
    buildTypes {
        release {
            // see: https://developer.android.com/build/shrink-code
            // Enables code shrinking, obfuscation, and optimization for only
            // your project's release build type. Make sure to use a build
            // variant with `isDebuggable=false`.
            minifyEnabled = true

            // Enables resource shrinking, which is performed by the
            // Android Gradle plugin.
            shrinkResources = true

            // Includes the default ProGuard rules files that are packaged with
            // the Android Gradle plugin. To learn more, go to the section about
            // R8 configuration files.
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            enableUnitTestCoverage true
            enableAndroidTestCoverage true
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
    buildFeatures {
        viewBinding true
        buildConfig true
    }

}

dependencies {

    // https://developer.android.com/build/multidex#groovy
    def multidex_version = "2.0.1"
    implementation "androidx.multidex:multidex:$multidex_version"

    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.appcompat:appcompat:1.6.1' // Last version to support minSDK 19
    implementation 'androidx.constraintlayout:constraintlayout:2.1.0' // Last version to support minSDK 19
    implementation 'androidx.navigation:navigation-fragment:2.7.7' // Last version to support minSDK 19
    implementation 'androidx.navigation:navigation-ui:2.7.7' // Last version to support minSDK 19
    implementation 'com.squareup.retrofit2:retrofit:2.6.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.6.0'
    implementation 'com.squareup.okhttp3:okhttp:3.12.13'
    // https://mvnrepository.com/artifact/com.google.guava/guava
    implementation 'com.google.guava:guava:32.1.2-jre'
    // https://howtodoinjava.com/retrofit2/logging-with-retrofit2/
    implementation("com.squareup.okhttp3:logging-interceptor:3.9.0")
    // https://github.com/vdurmont/semver4j
    implementation 'com.vdurmont:semver4j:3.1.0'
    // Support GIF Playback
    implementation 'com.github.bumptech.glide:glide:4.16.0'

    testImplementation 'junit:junit:4.13.2'
    testImplementation "org.mockito:mockito-core:5.10.0"

}