plugins {
    id 'com.android.library'
}

android {
    namespace 'com.aphex3k.eo1.ffmpeg'
    compileSdk 34

    defaultConfig {
        minSdk 19
        targetSdk 19
        ndk {
            abiFilters 'armeabi-v7a'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
}

def ffmpegAar = file('libs/ffmpeg-kit-min-gpl-lts.aar')

dependencies {
    if (ffmpegAar.exists()) {
        implementation files(ffmpegAar)
    }
    testImplementation 'junit:junit:4.13.2'
}
